import * as B from '../www/js/sicherung.js';
let fails = 0; const ok = (n, c, i = '') => { console.log((c ? 'OK   ' : 'FAIL ') + n + (i ? `  [${i}]` : '')); if (!c) fails++; };
const save = { universe: 153, akt: 1, runsDone: 9, complexity: 1e9, owned: [1, 2, 3], name: 'Äöü ✦ ☯' };
const b = B.packBackup(save, 1000);
ok('Datei-Round-Trip', B.parseBackup(B.toText(b)).ok);
const c = B.toCode(b), r = B.parseBackup(c);
ok('Code-Round-Trip inkl. Umlaute/Sonderzeichen', r.ok && r.backup.save.name === save.name && c.startsWith('SX144:'));
ok('Code mit Zeilenumbrüchen/Leerzeichen', B.parseBackup(c.slice(0, 20) + '\n  ' + c.slice(20)).ok);
const bad = JSON.parse(B.toText(b)); bad.save.complexity = 5;
ok('Manipulation → Prüfsumme schlägt an', !B.parseBackup(JSON.stringify(bad)).ok);
ok('Fremde Datei abgelehnt', !B.parseBackup('{"a":1}').ok && !B.parseBackup('quatsch').ok && !B.parseBackup('').ok);
ok('Abgeschnittener Code abgelehnt', !B.parseBackup(c.slice(0, c.length - 15)).ok);
const neu = JSON.parse(B.toText(b)); neu.format = 99; ok('neueres Format abgelehnt', !B.parseBackup(JSON.stringify(neu)).ok);
const inc = B.packBackup({ universe: 10, owned: [], complexity: 1 }); ok('Spielstand mit Universum <144 abgelehnt', !B.parseBackup(B.toText(inc)).ok);
let l = []; l = B.addSnapshot(l, save, 0); l = B.addSnapshot(l, save, 1000);
ok('Schnappschuss höchstens alle 20 h', l.length === 1);
l = B.addSnapshot(l, save, 21 * 3600e3); l = B.addSnapshot(l, save, 42 * 3600e3); l = B.addSnapshot(l, save, 63 * 3600e3);
ok('Ring hält nur 3, neuester zuerst', l.length === 3 && l[0].at === 63 * 3600e3);
ok('forcierter Schnappschuss', B.addSnapshot(l, save, 63 * 3600e3 + 5, true).length === 3);
const d = 86400e3, t = 100 * d;
ok('Erinnerung: nie gesichert', B.needsReminder({ universe: 150, runsDone: 5 }, t));
ok('keine Erinnerung am Anfang', !B.needsReminder({ universe: 144, runsDone: 0 }, t));
ok('keine Erinnerung nach frischer Sicherung', !B.needsReminder({ universe: 150, runsDone: 5, lastBackup: t - d }, t));
ok('Erinnerung nach 8 Tagen', B.needsReminder({ universe: 150, runsDone: 5, lastBackup: t - 8 * d }, t));
ok('nicht öfter als alle 3 Tage fragen', !B.needsReminder({ universe: 150, runsDone: 5, lastBackup: t - 8 * d, backupAsked: t - d }, t));
ok('Alterstext', B.ageText(0) === 'noch nie' && B.ageText(t - d, t) === 'gestern' && B.ageText(t - 3 * d, t) === 'vor 3 Tagen');
console.log(fails ? `FEHLGESCHLAGEN: ${fails}` : 'Alle Tests bestanden'); process.exit(fails ? 1 : 0);
