import * as K from '../www/js/kosmos.js';
import { newState } from '../www/js/economy.js';
let fails = 0; const ok = (n, c, i = '') => { console.log((c ? 'OK   ' : 'FAIL ') + n + (i ? `  [${i}]` : '')); if (!c) fails++; };
ok('Tipp-Haptik wächst mit der Epoche', K.tapHaptik(0) < K.tapHaptik(7) && K.tapHaptik(0) >= 4);
const l0 = K.leapHaptik(0), l7 = K.leapHaptik(7);
ok('Sprung-Crescendo: spätere Epochen mehr Impulse und länger', l7.length > l0.length && l7.at(-1) > l0.at(-1) && l7.every((x) => x > 0));
ok('Sprung-Wackeln wächst', K.leapShake(7) > K.leapShake(0));
ok('kein Ereignis vor Epoche 1', K.pickCosmos(0, null) === null);
ok('Epoche 1: nur Komet', K.pickCosmos(1, null).id === 'komet');
ok('nicht zweimal dasselbe hintereinander', K.pickCosmos(5, 'nova', () => 0.99).id !== 'nova' && K.pickCosmos(5, 'komet', () => 0).id !== 'komet');
const w1 = K.cosmosWait(true, () => 0), w2 = K.cosmosWait(false, () => 1);
ok('Wartezeiten', w1 === 150 && w2 === 480);
const d = K.COSMOS[0];
const a = K.cosmosOutcome(d, 'abwehren', 10, 5, 1000), u1 = K.cosmosOutcome(d, 'umlenken', 10, 5, 1000, () => 0), u2 = K.cosmosOutcome(d, 'umlenken', 10, 5, 1000, () => 0.9);
const n = K.cosmosOutcome(d, 'nutzen', 10, 5, 1000), x = K.cosmosOutcome(d, null, 10, 5, 1000);
ok('Abwehren: sicherer Ertrag, zählt als Kraft', a.win && a.gain > 0 && a.act === 'kraft' && !a.buff);
ok('Umlenken Treffer: großer Ertrag + Buff', u1.win && u1.gain > a.gain && u1.buff.k === 'prod');
ok('Umlenken Fehlschlag: mäßiger Verlust (6 %)', !u2.win && Math.abs(u2.gain + 60) < 1e-9);
ok('Nutzen: Tipp-Buff, zählt als Funke', n.win && n.buff.k === 'tap' && n.act === 'mutation');
ok('Verstreichen lassen: nichts passiert, keine Strafe', !x.win && x.gain === 0 && x.act === null);
const S = Object.assign(newState(), { universe: 150, runsDone: 5, epoch: 7, finished: true, avatars: ['mutter'], myths: [{ e: 4, id: 'kraft', name: 'Die Formende Hand' }], ending: 'lenker', law: 'nebel', taps: 1234, playTime: 3600 });
const f = K.buildFilm(S);
ok('Film: Start + 8 Epochen + Ende', f.length === 10 && f[0].kind === 'start' && f.at(-1).kind === 'ende');
ok('Film nennt Avatar der Epoche', f.some((s) => s.e === 1 && s.lines.some((l) => l.includes('Mutterzelle'))));
ok('Film nennt Mythos', f.some((s) => s.e === 4 && s.lines.some((l) => l.includes('Formende Hand'))));
ok('Film-Ende: Ende, Gesetz, Statistik', f.at(-1).lines.join('|').includes('Der Lenker') && f.at(-1).lines.join('|').includes('Dichter Nebel') && f.at(-1).lines.join('|').includes('1234 Berührungen'));
const S2 = Object.assign(newState(), { epoch: 2 }); ok('Film bei Epoche 2: nur bis dorthin', K.buildFilm(S2).filter((s) => s.kind === 'epoche').length === 3);
console.log(fails ? `FEHLGESCHLAGEN: ${fails}` : 'Alle Tests bestanden'); process.exit(fails ? 1 : 0);
