import * as N from '../www/js/entropie.js';
import * as E from '../www/js/economy.js';
let fails = 0; const ok = (n, c, i = '') => { console.log((c ? 'OK   ' : 'FAIL ') + n + (i ? `  [${i}]` : '')); if (!c) fails++; };
const S = (o = {}) => Object.assign(E.newState(), { runsDone: 6, epoch: 3, ...o });
ok('aktiv erst ab Durchlauf 4, nicht in Akt II / im Finale', !N.entActive(S({ runsDone: 2 })) && N.entActive(S({ runsDone: 3 })) && !N.entActive(S({ akt: 2 })) && !N.entActive(S({ finished: true })));
ok('Anstieg wächst mit Epoche und Durchlauf', N.entRate(S({ epoch: 7 })) > N.entRate(S({ epoch: 0 })) && N.entRate(S({ runsDone: 10 })) > N.entRate(S({ runsDone: 3 })));
ok('Anstieg: Ursuppe 0,05 %/s, Singularität ≈ 0,2–0,3 %/s', Math.abs(N.entRate(S({ epoch: 0, runsDone: 3 })) - 0.05) < 1e-9 && N.entRate(S({ epoch: 7, runsDone: 13 })) > 0.2 && N.entRate(S({ epoch: 7, runsDone: 13 })) < 0.32);
ok('offene Risse erhöhen den Anstieg', N.entRate(S(), 3) - N.entRate(S(), 0) > 0.14);
ok('Produktion bis 30 % unberührt, bei 100 % −40 %', N.entMult(S({ entropy: 30 })) === 1 && Math.abs(N.entMult(S({ entropy: 100 })) - 0.6) < 1e-9 && N.entMult(S({ entropy: 65 })) < 1 && N.entMult(S({ entropy: 65 })) > 0.6);
const st = S({ entropy: 60, owned: (() => { const o = new Array(24).fill(0); o[0] = 50; return o; })() });
const p0 = E.prodPerSec(S({ entropy: 0, owned: st.owned })), p1 = E.prodPerSec(st);
ok('prodPerSec berücksichtigt die Entropie', p1 < p0 && Math.abs(p1 / p0 - N.entMult(st)) < 1e-9, (p1 / p0).toFixed(3));
ok('Bosssiege geben dauerhaft +1,5 % (max 20)', Math.abs(N.bossBonus(S({ bossWins: 4 })) - 1.06) < 1e-9 && Math.abs(N.bossBonus(S({ bossWins: 99 })) - 1.3) < 1e-9);
const s2 = S({ entropy: 50 }); N.tick(s2, 10);
ok('tick: steigt, bleibt ≤ 100', s2.entropy > 50 && N.tick(S({ entropy: 99.99 }), 1000) === 100);
const s3 = S({ entropy: 50 }); N.relief(s3, 'mutation'); ok('Erleichterung Mutation −5', s3.entropy === 45); N.relief(s3, 'tap', 1000); ok('nie unter 0', s3.entropy === 5 || s3.entropy >= 0);
ok('Stufen 25/50/75', N.entStage(10) === 0 && N.entStage(25) === 1 && N.entStage(50) === 2 && N.entStage(75) === 3);
const s4 = S({ entropy: 10 }); N.offline(s4, 3600 * 8); ok('offline höchstens 50 %', s4.entropy <= 50 && s4.entropy > 10, String(s4.entropy));
const s5 = S({ entropy: 80 }); N.offline(s5, 3600); ok('offline senkt nie', s5.entropy === 80);
ok('Rhythmus: aktiver Spieler (4 Taps/s) hält die Entropie in Epoche 3 stabil', 4 * N.RELIEF.tap > N.entRate(S({ epoch: 3 })), `${4 * N.RELIEF.tap} vs ${N.entRate(S({ epoch: 3 })).toFixed(3)}`);
ok('Rhythmus: Einzelfinger (2 Taps/s) verliert in Epoche 7 langsam', 2 * N.RELIEF.tap < N.entRate(S({ epoch: 7, runsDone: 9 })));
ok('Bosse bei Epoche 2, 4, 6, 7 – je einmal pro Durchlauf', N.needsBoss(S(), 2) && N.needsBoss(S(), 7) && !N.needsBoss(S(), 3) && !N.needsBoss(S({ bossDone: [2] }), 2) && !N.needsBoss(S({ runsDone: 1 }), 2));
const d = N.BOSSES[2];
ok('Boss-HP wächst mit Entropie (max +50 %)', N.bossHP(d, 0) === 90 && N.bossHP(d, 100) === 135 && N.bossHP(d, 40) === 108);
ok('Boss ist machbar: 2 Taps/s + Schwachpunkte (Epoche 2)', 2 * d.dur + 10 * Math.floor(d.dur / d.weakEvery * 0.6) > N.bossHP(d, 40), String(2 * d.dur + 10 * Math.floor(d.dur / d.weakEvery * 0.6)));
const f = N.BOSSES[7];
ok('Finalboss ist machbar mit 3 Fingern (5 Taps/s)', 5 * f.dur + 10 * Math.floor(f.dur / f.weakEvery * 0.6) > N.bossHP(f, 40), String(4 * f.dur + 10 * Math.floor(f.dur / f.weakEvery * 0.6)) + ' vs ' + N.bossHP(f, 40));
const w = N.bossResult(S({ entropy: 70 }), 2, true, 10), l = N.bossResult(S({ entropy: 70 }), 2, false, 10), k = N.bossResult(S({ entropy: 100 }), 'kollaps', false, 10);
ok('Sieg: Entropie 8, Gewinn, Buff, +1 Sieg', w.entropy === 8 && w.gain === 1200 && w.buff && w.wins === 1);
ok('Niederlage Sprung-Boss: Entropie +25, kein Verlust', l.entropy === 95 && l.loss === 0 && l.wins === 0);
ok('Niederlage Kollaps: −20 % Komplexität, Entropie 60', k.loss === 0.2 && k.entropy === 60);
console.log(fails ? `FEHLGESCHLAGEN: ${fails}` : 'Alle Tests bestanden'); process.exit(fails ? 1 : 0);
